"""developer-portal: UI serving + server-side proxy to partner-auth/gateway."""

from __future__ import annotations

import httpx
import pytest
from fastapi.testclient import TestClient

import main


class _Resp:
    def __init__(self, status=200, json_data=None):
        self.status_code = status
        self._json = json_data

    def json(self):
        if self._json is None:
            raise ValueError("no json")
        return self._json


class _Calls(list):
    """A list that can carry a mutable ``state`` for the fake transport."""


@pytest.fixture()
def calls(monkeypatch):
    monkeypatch.setenv("PARTNER_AUTH_URL", "http://partner-auth")
    monkeypatch.setenv("GATEWAY_URL", "http://gateway")
    recorded = _Calls()
    state = {"reachable": True}

    def fake_request(method, url, json=None, params=None, headers=None, timeout=None):
        recorded.append({"method": method, "url": url, "json": json, "headers": headers})
        if not state["reachable"]:
            raise httpx.ConnectError("down")
        if url.endswith("/v1/partner/keys") and method == "POST":
            return _Resp(200, {"key_id": "pk_sandbox_x", "token": "pk_sandbox_x.secret"})
        if url.endswith("/v1/partner/keys") and method == "GET":
            return _Resp(200, {"keys": [{"key_id": "pk_sandbox_x", "scopes": ["onramp"], "active": True}]})
        if "/rotate" in url:
            return _Resp(200, {"key_id": "pk_sandbox_x", "token": "pk_sandbox_x.newsecret"})
        if "/revoke" in url:
            return _Resp(200, {"key_id": "pk_sandbox_x", "active": False})
        if "/api/" in url:  # gateway proxy
            return _Resp(200, {"fee": 1600.0, "dest_amount": 99.0})
        return _Resp(404, {"error": "unmapped"})

    monkeypatch.setattr(httpx, "request", fake_request)
    recorded.state = state  # type: ignore[attr-defined]
    return recorded


@pytest.fixture()
def client(calls):
    c = TestClient(main.app)
    c.calls = calls  # type: ignore[attr-defined]
    return c


def test_index_serves_html(client):
    r = client.get("/")
    assert r.status_code == 200 and "text/html" in r.headers["content-type"]
    assert "Developer Portal" in r.text


def test_issue_key_proxies_partner_auth(client):
    r = client.post("/portal/keys", json={"tenant_id": "ten_1", "scopes": ["onramp"]})
    assert r.json()["token"] == "pk_sandbox_x.secret"
    call = client.calls[0]
    assert call["url"] == "http://partner-auth/v1/partner/keys"
    assert call["json"] == {"tenant_id": "ten_1", "scopes": ["onramp"]}


def test_list_rotate_revoke_proxy(client):
    assert client.get("/portal/keys", params={"tenant": "ten_1"}).json()["keys"][0]["key_id"] == "pk_sandbox_x"
    assert client.post("/portal/keys/pk_sandbox_x/rotate").json()["token"].endswith("newsecret")
    assert client.post("/portal/keys/pk_sandbox_x/revoke").json()["active"] is False


def test_playground_proxies_through_gateway_with_bearer(client):
    r = client.post("/portal/proxy", json={
        "token": "pk_sandbox_x.secret", "method": "POST", "service": "onramp",
        "path": "v1/onramp/quotes", "body": {"source_currency": "NGN", "dest_asset": "USDC", "amount": 160000},
    })
    out = r.json()
    assert out["status"] == 200 and out["response"]["dest_amount"] == 99.0
    call = client.calls[-1]
    assert call["url"] == "http://gateway/api/onramp/v1/onramp/quotes"
    assert call["headers"]["authorization"] == "Bearer pk_sandbox_x.secret"


def test_unreachable_upstream_502(client):
    client.calls.state["reachable"] = False
    r = client.post("/portal/keys", json={"tenant_id": "ten_1", "scopes": []})
    assert r.status_code == 502 and r.json()["error"]["code"] == "upstream_unreachable"


def test_services_catalog_reads_generated_specs(client):
    # The repo has docs/api-catalog/*.openapi.json generated by build_api_catalog.py.
    body = client.get("/portal/services").json()
    assert body["count"] >= 1
    assert "partner-auth" in body["services"]
