#!/usr/bin/env python3
"""Generate a developer-facing API catalog for the API plane (docs/06, docs/12).

Every API-plane service is a FastAPI app, so each already exposes an OpenAPI
schema. This collects them into one catalog — the core "API docs" developer-
onboarding asset (docs/12) and the concrete form of docs/06's "expand into
OpenAPI-ready definitions".

Each service's schema is extracted in its OWN subprocess: services are designed to
be self-contained with the repo root + their own dir on PYTHONPATH, and many share
flat module names (main, models), so importing several in one process would
collide. One subprocess per service sidesteps that entirely.

Outputs (under docs/api-catalog/):
  <service>.openapi.json   raw OpenAPI 3.x schema per service
  README.md                human index: every route, grouped by service

Run:  python3 scripts/build_api_catalog.py
"""

from __future__ import annotations

import json
import os
import subprocess
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_DIR = os.path.join(REPO_ROOT, "docs", "api-catalog")

# API-plane FastAPI services (dir name under services/).
SERVICES = [
    "public-api-gateway",
    "partner-auth",
    "routing-service",
    "onramp-orchestrator",
    "offramp-orchestrator",
    "wallet-service",
    "settlement-status",
    "webhook-service",
    "api-metering",
    "tenant-billing",
]

# Printed to stdout by the child so we can split it from any import noise.
_DUMP = (
    "import json,main;"
    "print('<<OPENAPI>>'+json.dumps(main.app.openapi())+'<<END>>')"
)


def extract_openapi(service: str) -> dict | None:
    """Run a child process that imports the service and dumps its OpenAPI schema."""
    svc_dir = os.path.join(REPO_ROOT, "services", service)
    env = dict(os.environ)
    env["PYTHONPATH"] = f"{REPO_ROOT}:{svc_dir}"
    env.pop("GCP_PROJECT_ID", None)  # keep services in local mode
    try:
        proc = subprocess.run(
            [sys.executable, "-c", _DUMP],
            cwd=svc_dir, env=env, capture_output=True, text=True, timeout=60,
        )
    except subprocess.TimeoutExpired:
        print(f"  ! {service}: timed out", file=sys.stderr)
        return None
    if proc.returncode != 0:
        print(f"  ! {service}: import failed\n{proc.stderr.strip()[-500:]}", file=sys.stderr)
        return None
    out = proc.stdout
    if "<<OPENAPI>>" not in out or "<<END>>" not in out:
        print(f"  ! {service}: no schema in output", file=sys.stderr)
        return None
    raw = out.split("<<OPENAPI>>", 1)[1].split("<<END>>", 1)[0]
    return json.loads(raw)


def routes_of(spec: dict) -> list[tuple[str, str, str]]:
    """(METHOD, path, summary) for each operation, skipping FastAPI's own docs."""
    rows = []
    for path, ops in sorted(spec.get("paths", {}).items()):
        if path in ("/openapi.json", "/docs", "/docs/oauth2-redirect", "/redoc"):
            continue
        for method, op in ops.items():
            if method.lower() not in ("get", "post", "put", "patch", "delete"):
                continue
            summary = op.get("summary") or (op.get("description", "").splitlines()[0] if op.get("description") else "")
            rows.append((method.upper(), path, summary))
    return rows


def main() -> int:
    os.makedirs(OUT_DIR, exist_ok=True)
    catalog: dict[str, dict] = {}
    for service in SERVICES:
        print(f"- {service}")
        spec = extract_openapi(service)
        if spec is None:
            continue
        catalog[service] = spec
        with open(os.path.join(OUT_DIR, f"{service}.openapi.json"), "w") as f:
            json.dump(spec, f, indent=2, sort_keys=True)

    # Human-readable index.
    lines = [
        "# API Catalog (sandbox API plane)",
        "",
        "Auto-generated by `scripts/build_api_catalog.py` from each service's live",
        "OpenAPI schema (docs/06, docs/12). Per-service raw schemas are the",
        "`*.openapi.json` files in this directory. SANDBOX — live rails gated on",
        "licensing (docs/REGULATORY_BRIEF.md).",
        "",
        f"Services: {len(catalog)} / {len(SERVICES)}",
        "",
    ]
    total_routes = 0
    for service in SERVICES:
        spec = catalog.get(service)
        if spec is None:
            lines += [f"## {service}", "", "_schema unavailable_", ""]
            continue
        rows = routes_of(spec)
        total_routes += len(rows)
        lines += [f"## {service}", ""]
        for method, path, summary in rows:
            lines.append(f"- `{method:6} {path}`" + (f" — {summary}" if summary else ""))
        lines.append("")
    lines += [f"_Total documented routes: {total_routes}_", ""]

    with open(os.path.join(OUT_DIR, "README.md"), "w") as f:
        f.write("\n".join(lines))

    print(f"\nWrote {len(catalog)}/{len(SERVICES)} service schemas + README.md to docs/api-catalog/")
    print(f"Total documented routes: {total_routes}")
    return 0 if len(catalog) == len(SERVICES) else 1


if __name__ == "__main__":
    raise SystemExit(main())
